version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel-app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/vendor:/var/www/vendor
      - ./backend/node_modules:/var/www/node_modules
    networks:
      - app-network
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: vue-app
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge